[package]
name = "rusty-scrapyard-rv64-virt"
version = "0.0.1"
edition = "2024"
authors = [ "r0cknr011a" ]

[dependencies]
rusty-scrapyard-lib = { path = "../lib" }
rusty-scrapyard-iomem = { path = "../iomem" }
rusty-scrapyard-cpu = { path = "../cpu" }
