[package]
name = "toolkit"
version = "0.0.3"
edition = "2024"
authors = [ "r0cknr011a" ]

[dependencies]
toolkit-unsafe = { path = "../unsafe" }

[lints.clippy]
panic = "deny"
unwrap_used = "deny"
expect_used = "deny"
